#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-GB"
title: "Ben Mepham"
title_separator: "-"
#subtitle: ""
name: "Ben Mepham"
#email:
logo: "/assets/images/b-icon.png"
#teaser: #set default teaser image
description: "Ben Mepham's personal website and blog"
url: "https://bjm.me.uk"
repository: "benmepham/benmepham.github.io"
twitter_username: benjmepham
github_username: benmepham
minimal_mistakes_skin: default
search: true

# Comments
comments:
    provider: "utterances" # false (default), "disqus", "discourse", "facebook", "staticman_v2", "staticman", "utterances", "custom"
    utterances:
        theme: # "github-light" (default), "github-dark"
        issue_term: # "pathname" (default)

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London

include:
    - _pages

#  Exclude from processing.
#  The following items will not be processed, by default. Create a custom list
#  to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - docker-compose.yml
    - README.md
    - CNAME
    - .gitignore
    - site.code-workspace

# Plugins (previously gems:)
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-gist
    - jekyll-feed
    - jemoji
    - jekyll-include-cache

author:
    name: "Ben"
    avatar: "/assets/images/bio-photo.jpg"
    bio: "Tech Enthusiast and Computer Science Student"
    location: "UK"
    links:
        - label: "Twitter"
          icon: "fab fa-fw fa-twitter-square"
          url: "https://twitter.com/benjmepham"
        - label: "GitHub"
          icon: "fab fa-fw fa-github"
          url: "https://github.com/benmepham"
        - label: "Linkedin"
          icon: "fab fa-fw fa-linkedin"
          url: "https://www.linkedin.com/in/benmepham"

footer:
    links:
        - label: "Twitter"
          icon: "fab fa-fw fa-twitter-square"
          url: "https://twitter.com/benjmepham"
        - label: "GitHub"
          icon: "fab fa-fw fa-github"
          url: "https://github.com/benmepham"
        - label: "Linkedin"
          icon: "fab fa-fw fa-linkedin"
          url: "https://www.linkedin.com/in/benmepham"

defaults:
    # _posts
    - scope:
          path: ""
          type: posts
      values:
          layout: single
          author_profile: true
          read_time: true
          comments: true
          share: true
          related: true
          show_date: true
    # _pages
    - scope:
          path: "_pages"
          type: pages
      values:
          layout: single
          author_profile: true

category_archive:
    type: liquid
    path: /categories/
tag_archive:
    type: liquid
    path: /tags/
